language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# need "python setup.py install" to install resync so that client tests work
install:
  - pip install requests
  - pip install python-dateutil
  - pip install coveralls
  - python setup.py install
script:
  - py.test 
  - coverage run --source=sbrew setup.py test
after_success:
  - coveralls
